---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	retrieve(retrieve)
	enrich(enrich)
	junior_a(junior_a)
	junior_b(junior_b)
	__end__([<p>__end__</p>]):::last
	__start__ --> retrieve;
	enrich --> junior_a;
	enrich --> junior_b;
	retrieve --> enrich;
	junior_a --> __end__;
	junior_b --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
